---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: All
  create: all
  match: "**/*"
- type: directory
  path: pages
  label: All content
  create: all
  match: src/pages/*
- type: directory
  path: src/pages/posts
  label: Posts
  create: all
  match: src/pages/posts
  templates:
  - blog-post
- type: directory
  path: src/pages/pages
  label: Basic pages
  create: all
  match: src/pages/pages
  templates:
  - basic-page
- type: directory
  path: src/pages/listings
  label: Blog listings
  create: all
  match: src/pages/listings
  templates:
  - blog-listing
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
